### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by benreyn** [hzenginx/spacelite#1]
I love the idea of this project, mostly because spacemacs itself has gotten so large that its hard to know where to start reading its source and things have gotten so bloated. What are your plans for this repo? Is the recommendation to just fork it and add packages / make customizations, or is there a plan to make this a "competing" emacs / evil distribution that does its best to stay as lightweight as possible?

**Comment by huseyz** [comment]
Hi @benreyn,

Unfortunately I no longer use this config daily. Mostly because [ensime](https://github.com/ensime/ensime-server) is not maintened anymore and intellij tools provides a better user experience for my work. 
If you have any interest to use the spacelite as a base for something like you mentioned please feel free to do so. In the meantime I don't think I will continue improving or maintaining this repo in near future.

**Comment by benreyn** [comment]
Thanks @hzenginx! Ill probably start a fork under a github organization and see if there is any interest from the community. If not I'll just maintain it for my personal use. Love what you've done here! I appreciate the work you put into it!

Would you mind if I kept the original name of the project or would you like me to rename it? (I only ask because `spacelite` is such a great name given the goal)

**Comment by huseyz** [comment]
> Would you mind if I kept the original name of the project or would you like me to rename it? (I only ask because spacelite is such a great name given the goal)

Feel free
